name: Release new version

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo files
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: cargo test --release
      - name: Test with standalone feature
        run: cargo test --features standalone --release

  # TODO: Add steps to publish tarball to the AUR
  publish:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo files
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build realease binary
        run: cargo build --release
      - name: Generate release tarball
        run: tar czf release.tar.gz share target/release/rsc
      - name: Set VERSION environment variable
        run: |
          version=$(echo $GITHUB_REF | cut -d '/' -f3)
          echo "::set-env name=VERSION::$version"
      - name: Publish release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.gz
          body_path: changelogs/${{ env.VERSION }}.md
